image: python:3.7-alpine

stages:
  - test
  - cibuild
  - stage
  - release

variables:
  BUILD_DIR: Build
  BUILDER: ./build.py

before_script:
  - python -V
  - pip install pipenv
  - pipenv sync
  - cd $BUILD_DIR
  - $BUILDER $CI_JOB_STAGE $USER

cache:
  paths:
    - .local/share/virtualenvs

test:
  stage: test
  script:
    - echo Done with test stage
  artifacts:
    paths:
      - $BUILD_DIR/unit_test_results

build:
  stage: cibuild
  script:
    - echo Done with build stage
  artifacts:
    paths:
      - $BUILD_DIR/artifacts

staging_deploy:
  stage: stage
  environment: Staging
  script:
    - echo Done with staging deploy test
  only:
    - master
  when: manual

production_deploy:
  stage: release
  environment: Production
  script:
    - echo Done with release
  only:
    - master
  when: manual
