image: python:3.10-slim

stages:
  - static_analysis
  - unit_tests
  - build
  - install_test
  - publish_test
  - publish

variables:
  PRODUCT: BatCave
  ARTIFACTS_DIR: dist
  UNIT_TEST_DIR: unit_test_results
  PYPI_PKG: dist/$PRODUCT-$RELEASE.tar.gz
  RELEASE: 42.0.0
  GIT_AUTHOR_NAME: $GITLAB_USER_NAME
  GIT_AUTHOR_EMAIL: $GITLAB_USER_EMAIL
  GIT_COMMITTER_NAME: $GITLAB_USER_NAME
  GIT_COMMITTER_EMAIL: $GITLAB_USER_EMAIL

cache:
  paths:
    - .local/share/virtualenvs

.builder:
  except:
    - tags
  before_script:
    - cat /etc/os-release
    - python -V
    - apt-get -y update
    - apt-get -y install build-essential git libffi-dev libssl-dev
    - python -m pip install -U pip
    - pip install -U setuptools wheel
  script:
    - exit 1

static_analysis:
  stage: static_analysis
  extends: .builder
  script:
    - pip install -e .[stest]
    - pylint batcave
    - flake8 batcave
    - mypy --install-types batcave

unit_tests:
  stage: unit_tests
  extends: .builder
  script:
    - pip install -e .[utest]
    - python -m xmlrunner discover -o $UNIT_TEST_DIR
  artifacts:
    reports:
      junit: $UNIT_TEST_DIR/*

build:
  stage: build
  extends: .builder
  script:
    - pip install -e .[build]
    - python -m build
  artifacts:
    paths:
      - $ARTIFACTS_DIR

install_test:
  stage: install_test
  except:
    - tags
  before_script:
    - echo Testing install
  script:
    - pip install $PYPI_PKG

.publisher:
  extends: .builder
  only:
    - master
    - /^release\/.*$/
  when: manual
  allow_failure: false

publish_test:
  stage: publish_test
  environment: Staging
  extends: .publisher
  variables:
    BUILD_ARGS: test $GITLAB_USER_LOGIN $GITLAB_USER_TOKEN $PYPI_TEST_TOKEN

publish:
  stage: publish
  environment: Production
  extends: .publisher
  variables:
    BUILD_ARGS: $RELEASE $GITLAB_USER_LOGIN $GITLAB_USER_TOKEN $PYPI_PRODUCTION_TOKEN

# cSpell:ignore pypi virtualenvs batcave stest mypy utest xmlrunner
