image: python:3.7-alpine

stages:
  - unit_tests
  - ci_build
  - install_test
  - publish_test
  - publish

variables:
  PRODUCT: BatCave
  BUILD_DIR: Build
  ARTIFACTS_DIR: $BUILD_DIR/artifacts
  PYPI_PKG: $BUILD_DIR/artifacts/$PRODUCT-$RELEASE.tar.gz
  PYPI_WHEEL: $BUILD_DIR/artifacts/$PRODUCT-$RELEASE-py3-none-any.whl
  BUILDER: pipenv run python build.py $CI_JOB_STAGE $BUILD_ARGS $PASSWORD_ARG
  RELEASE: 37.0.1

before_script:
  - python -V
  - pip install pipenv
  - pipenv sync
  - cd $BUILD_DIR

.publish_args:
  variables:
    PASSWORD_ARG: --password $PASSWORD

cache:
  paths:
    - .local/share/virtualenvs

unit_tests:
  stage: unit_tests
  script:
    - $BUILDER
  artifacts:
    reports:
      junit: $BUILD_DIR/unit_test_results/*

ci_build:
  stage: ci_build
  variables:
    BUILD_ARGS: --build-num $CI_JOB_ID --release $RELEASE
  script:
    - $BUILDER
  artifacts:
    paths:
      - $ARTIFACTS_DIR

install_test:
  stage: install_test
  image: python:3.7
  before_script:
    - echo Testing install
  script:
    - pip install $PYPI_PKG

publish_test:
  stage: publish_test
  environment: Staging
  extends: .publish_args
  script:
    - TMP_RELEASE=$RANDOM
    - cd ..
    - mv $PYPI_PKG $ARTIFACTS_DIR/$PRODUCT-$TMP_RELEASE.tar.gz
    - mv $PYPI_WHEEL $ARTIFACTS_DIR/$PRODUCT-$TMP_RELEASE-py3-none-any.whl
    - cd $BUILD_DIR
    - $BUILDER
    - apt-get install git
    - git tag v$RELEASE
    - git push origin --tags
  only:
    - master
  when: manual

publish:
  stage: publish
  environment: Production
  extends: .publish_args
  script:
    - $BUILDER
  only:
    - master
  when: manual

