image: python:3.10-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_BRANCH =~ /^feature\/.*/

stages:
  - static_analysis
  - unit_tests
  - build
  - install_test
  - publish_test
  - release

variables:
  PRODUCT: batcave
  VIRTUAL_ENV: venv
  ARTIFACTS_DIR: dist
  UNIT_TEST_DIR: unit_test_results
  GIT_AUTHOR_NAME: $GITLAB_USER_NAME
  GIT_AUTHOR_EMAIL: $GITLAB_USER_EMAIL
  GIT_COMMITTER_NAME: $GITLAB_USER_NAME
  GIT_COMMITTER_EMAIL: $GITLAB_USER_EMAIL

.base:
  variables:
    FLIT_ROOT_INSTALL: 1
  before_script:
    - cat /etc/os-release
    - python -V
    - apt-get update
    - apt-get -y -qq --no-install-recommends install git
    - python -m pip install -U pip
    - pip install -U setuptools wheel
    - pip install -U virtualenv
    - if [ ! -e $VIRTUAL_ENV ]; then virtualenv $VIRTUAL_ENV; fi
    - source $VIRTUAL_ENV/bin/activate
    - python -m pip install -U pip
    - pip install -U setuptools wheel
    - pip install -U flit
    - flit install -s --deps all
  cache:
    paths:
      - $VIRTUAL_ENV

static_analysis:
  stage: static_analysis
  extends: .base
  script:
    - pylint $PRODUCT
    - flake8 $PRODUCT
    - mypy $PRODUCT

unit_tests:
  stage: unit_tests
  extends: .base
  script:
    - python -m xmlrunner discover -o $UNIT_TEST_DIR
  artifacts:
    reports:
      junit: $UNIT_TEST_DIR/*

build:
  stage: build
  extends: .base
  script:
    - flit build
  artifacts:
    paths:
      - $ARTIFACTS_DIR

install_test:
  stage: install_test
  script:
    - pip install $ARTIFACTS_DIR/*.tar.gz

.publisher:
  extends: .base
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_BRANCH =~ /^feature\/.*/
      when: manual
      allow_failure: false
  script:
    - git remote add gitlab_pipeline_origin https://$GITLAB_USER_NAME:$GITLAB_USER_TOKEN@gitlab.com/arisilon/batcave.git
    - twine upload --config-file $PYPIRC -r $PYPI_REPO $ARTIFACTS_DIR/*
    - bumpver update $BUMP_ARG
    - if [ $BUMPVER_PUSH == false ]; then git push gitlab_pipeline_origin HEAD:$CI_COMMIT_BRANCH; fi

publish_test:
  stage: publish_test
  environment: Staging
  extends: .publisher
  variables:
    PYPI_REPO: testpypi
    BUMP_ARG: --tag-num --no-tag-commit --no-push
    BUMPVER_PUSH: "false"

release:
  stage: release
  environment: Production
  extends: .publisher
  variables:
    PYPI_REPO: pypi
    BUMP_ARG: --minor

# cSpell:ignore batcave pypi virtualenvs mypy xmlrunner pypirc testpypi virtualenv venv
