image: python:3.7-alpine

stages:
  - unit_tests
  - ci_build
  - install_test
  - publish_test
  - release
  - publish

variables:
  BUILD_DIR: Build
  BUILDER: python build.py
  RELEASE: 37.0.1

before_script:
  - python -V

.use_builder:
  script:
    - pip install pipenv
    - pipenv sync
    - cd $BUILD_DIR
    - pipenv run $BUILDER $CI_JOB_STAGE $BUILD_ARGS $PASSWORD_ARG

.publish_args:
  variables:
    PASSWORD_ARG: --password $PASSWORD

cache:
  paths:
    - .local/share/virtualenvs

unit_tests:
  stage: unit_tests
  extends: .use_builder
  artifacts:
    reports:
      junit: $BUILD_DIR/unit_test_results/*

ci_build:
  stage: ci_build
  extends: .use_builder
  variables:
    BUILD_ARGS: --build-num $CI_JOB_ID --release $RELEASE
  artifacts:
    paths:
      - $BUILD_DIR/artifacts

install_test:
  stage: install_test
  image: python:3.7
  script:
    - pip install $BUILD_DIR/artifacts/BatCave-$RELEASE.tar.gz

publish_test:
  stage: publish_test
  environment: Staging
  extends: 
    - .use_builder
    - .publish_args
  only:
    - master
  when: manual

publish:
  stage: publish
  environment: Production
  extends: 
    - .use_builder
    - .publish_args
  only:
    - master
  when: manual

release:
    stage: release
    environment: Staging
    script:
        git tag v$RELEASE
        git push origin --tags
    