image: python:3.7-alpine

stages:
  - unit_tests
  - ci_build
  - install_test
  - publish_test
  - publish
  - release_test

variables:
  PRODUCT: BatCave
  BUILD_DIR: Build
  ARTIFACTS_DIR: $BUILD_DIR/artifacts
  UNIT_TEST_DIR: $BUILD_DIR/unit_test_results
  PYPI_PKG: $BUILD_DIR/artifacts/$PRODUCT-$RELEASE.tar.gz
  BUILDER: pipenv run python build.py $CI_JOB_STAGE $BUILD_ARGS $PASSWORD_ARG
  RELEASE: 37.0.1

before_script:
  - python -V
  - pip install pipenv
  - pipenv sync
  - cd $BUILD_DIR

cache:
  paths:
    - .local/share/virtualenvs

unit_tests:
  stage: unit_tests
  script:
    - $BUILDER
  artifacts:
    reports:
      junit: $UNIT_TEST_DIR

ci_build:
  stage: ci_build
  variables:
    BUILD_ARGS: --build-num $CI_JOB_ID --release $RELEASE
  script:
    - $BUILDER
  artifacts:
    paths:
      - $ARTIFACTS_DIR

install_test:
  stage: install_test
  image: python:3.7
  before_script:
    - echo Testing install
  script:
    - pip install $PYPI_PKG

publish_test:
  stage: publish_test
  environment: Staging
  variables:
    PASSWORD_ARG: --password $TEST_TOKEN
  script:
    - $BUILDER
  only:
    - master
  when: manual
  allow_failure: false

release_test:
  stage: release_test
  image: python:3.7
  script:
  only:
    - master
  when: manual
  allow_failure: false

publish:
  stage: publish
  image: python:3.7
  environment: Production
  variables:
    PASSWORD_ARG: --password $PRODUCTION_TOKEN
  script:
    - $BUILDER
    - git remote add user_origin https://$GITLAB_USER_LOGIN:$USER_PASSWORD@gitlab.com/arisilon/batcave.git
    - git tag v$RELEASE
    - git push user_origin --tags
  only:
    - master
  when: manual
  allow_failure: false
