image: python:3.7-alpine

stages:
  - unit_tests
  - ci_build
  - install_test
  - publish_test
  - publish

variables:
  BUILD_DIR: Build
  BUILDER: python build.py

before_script:
  - python -V

.use_builder:
  script:
    - pip install pipenv
    - pipenv sync
    - cd $BUILD_DIR
    - pipenv run $BUILDER $CI_JOB_STAGE $USER

cache:
  paths:
    - $BUILD_DIR/build_info.txt
    - .local/share/virtualenvs

unit_tests:
  stage: unit_tests
  extends: .use_builder
  artifacts:
    reports:
      junit: $BUILD_DIR/unit_test_results/*

ci_build:
  stage: ci_build
  extends: .use_builder
  artifacts:
    paths:
      - $BUILD_DIR/artifacts

install_test:
  stage: install_test
  script:
    - RELEASE=`cat $BUILD_DIR/build_info.txt | python -c "import sys;release=[l.split('=')[1].strip() for l in sys.stdin if 'release=' in l][0];print(release)"`
    - pip install $BUILD_DIR/artifacts/BatCave-$RELEASE.tar.gz

publish_test:
  stage: publish_test
  environment: Staging
  extends: .use_builder
  only:
    - master
  when: manual

publish:
  stage: publish
  environment: Production
  extends: .use_builder
  only:
    - master
  when: manual
