[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]

name = "tCave"  # batcave.__title__,
version = "42.0.0"  # batcave.__version__,

description = "Python Programming Toolkit"  # batcave.__summary__,
readme = "DOCUMENTATION.md"
license = {text = "MIT"} # batcave.__license__,

authors = [
    {name = "Jeffery G. Smith", email = "web@pobox.com"}  # batcave.__author__, batcave.__email__
]

requires-python = "~=3.10"
keywords = ["python", "programming", "utilities"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",

    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",

    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Natural Language :: English",
]

dependencies = [
    "docker ~= 6.1",
    "GitPython ~= 3.1",
    "google-cloud",
    "kubernetes ~= 26.1",
    "requests ~= 2.30",
    "WMI ~= 1.5; sys_platform == 'win32'",
    "psutil ~= 5.9; platform_machine not in 'arm arm64 armv6l armv7l armv8b armv8l'",
    "PyQt5 ~= 5.15; platform_machine not in 'aarch64 aarch64_be arm arm64 armv6l armv7l armv8b armv8l'"
]
# package_data={'batcave': ['py.typed']}

[project.optional-dependencies]
stest = [
    "flake8", 
    "flake8-annotations", 
    "flake8-pyproject", 
    "mypy", 
    "pylint", 
    "PyQt5-stubs",
    "types-PyYAML",
    "types-psutil",
    "types-requests"
]
utest = ["xmlrunner"]
publish = ["twine"]

[project_urls]
homepage = "https://gitlab.com/arisilon/batcave/"  # batcave.__uri__,
documentation = "https://batcave.readthedocs.io"
repository = "https://gitlab.com/arisilon/batcave/"
changelog = "https://gitlab.com/arisilon/batcave/-/blob/master/CHANGELOG.md"

[tool.flake8]
max-line-length = 200
ignore = ["ANN002", "ANN003", "ANN101", "ANN204", "ANN401"]
[tool.pylint.format]
max-line-length = 200

[tool.pylint.design]
max-attributes = 10

[tool.pylint.messages_control]
disable = ["duplicate-code" , "fixme"]

[[tool.mypy.overrides]]
module = "docker.*"
ignore_missing_imports = true

# [mypy-git.*]
# ignore_missing_imports = True

[[tool.mypy.overrides]]
module = "kubernetes.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "P4.*"
ignore_missing_imports = true

# [mypy-pywintypes.*]
# ignore_missing_imports = True

# [mypy-setuptools.*]
# ignore_missing_imports = True

# [mypy-xmlrunner.*]
# ignore_missing_imports = True

# [mypy-win32api.*]
# ignore_missing_imports = True

# [mypy-win32com.*]
# ignore_missing_imports = True

# [mypy-win32con.*]
# ignore_missing_imports = True

# [mypy-win32typing.*]
# ignore_missing_imports = True

# [mypy-wmi.*]
# ignore_missing_imports = True
