# TODO:
# - limit publish to master and release branches and push only
# - Create release
# - Determine how to get bumpver to work with branch restrictions.

name: BatCave
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ARTIFACTS_DIR: dist
  FLIT_ROOT_INSTALL: 1
  GIT_AUTHOR_NAME: "${{ github.triggering_actor }}"
  GIT_AUTHOR_EMAIL: "${{ github.triggering_actor }}@users.noreply.github.com"
  PYTHON_BUILD_VER: "3.10"
  UNIT_TEST_DIR: unit_test_results
  VIRTUAL_ENV: venv

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}
      - run: cicd-support/cicd.sh "${{ github.job }}"

  unit-tests:
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}
      - run: cicd-support/cicd.sh "${{ github.job }}"
        if: matrix.os != 'windows-latest'
      - run: "cicd-support/${{ github.job }}.ps1"
        if: matrix.os == 'windows-latest'
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && (matrix.os == 'ubuntu-latest')
        with:
          check_name: ${{ matrix.os }} ${{ matrix.python-version }} Unit Tests
          files: ${{ env.UNIT_TEST_DIR }}/*.xml
      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always() && (matrix.os != 'ubuntu-latest')
        with:
          check_name: ${{ matrix.os }} ${{ matrix.python-version }} Unit Tests
          files: ${{ env.UNIT_TEST_DIR }}/*.xml

  build:
    needs:
      - static-analysis
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_BUILD_VER }}
          cache: "pip"
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-3.10
      - run: cicd-support/cicd.sh "${{ github.job }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}

  install-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_BUILD_VER }}
      - uses: actions/download-artifact@v4
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-3.10
      - run: cicd-support/cicd.sh "${{ github.job }}"

  publish-test:
    needs: install-test
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_BUILD_VER }}
      - uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}
      - run: cicd-support/cicd.sh "${{ github.job }}"

  publish:
    needs: publish-test
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_BUILD_VER }}
      - uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.VIRTUAL_ENV }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }}
      - run: cicd-support/cicd.sh "${{ github.job }}"

# cSpell:ignore virtualenv pypirc batcave venv cicd pypi testpypi bumpver noreply pypa
