name: Test Messaging
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo Second job
  job3:
    needs:
      - job1
      - job2
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summarize dependency results
        run: |
          failed=()
          if [[ "${{ needs.job1.result }}" != "success" ]]; then failed+=("job1"); fi
          if [[ "${{ needs.job2.result }}" != "success" ]]; then failed+=("job2"); fi
          if [[ ${#failed[@]} -gt 0 ]]; then
            echo "Failed dependencies: ${failed[*]}"
          else
            echo "Failed dependencies: none"
          fi
